print ("aqsa fiaz")
print(2+3)
print("we are learning form codanics ")
print("hello")
print("i am form taunsa sharif ")
print("now for higher study i move to fsd ")
print("i am learning data science ")
print("i am passonated about data science ")
print("i want to get job at google ")
print("i have big dream , not for myself but my family my area  ")